# Generated by Django 4.2.9 on 2024-02-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='driving_licence',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
