# Generated by Django 4.2.9 on 2024-02-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapps', '0002_customusers_driving_licence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ending_day',
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
